### ISSUE TITLE
Getting error when starting

### ISSUE THREAD

**Issue by adagi** [rodjun/python_csgo_radar#5]
Hey, I found this project today and thought it was very interesting. I wanted to try it now, I already installed all the required modules and replaced all the "client.dll" with "client_panorama.dll" because of panorama UI. Dou you know why I still get this crash?

F:\Downloads\py\python_csgo_radar-master>python csgo_hack_pygame.py
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
hwnd: 663684
pid: c_long(7308)
1276
Traceback (most recent call last):
  File "csgo_hack_pygame.py", line 124, in <module>
    not_a_hack = CSGORadar()
  File "csgo_hack_pygame.py", line 30, in __init__
    if self.process.get_module_size("client_panorama.dll") != offsets["modules"]["client_panorama.dll"]["size"]:
KeyError: 'modules'

**Comment by kir486680** [comment]
> Hey, I found this project today and thought it was very interesting. I wanted to try it now, I already installed all the required modules and replaced all the "client.dll" with "client_panorama.dll" because of panorama UI. Dou you know why I still get this crash?
> 
> F:\Downloads\py\python_csgo_radar-master>python csgo_hack_pygame.py
> pygame 1.9.4
> Hello from the pygame community. https://www.pygame.org/contribute.html
> hwnd: 663684
> pid: c_long(7308)
> 1276
> Traceback (most recent call last):
> File "csgo_hack_pygame.py", line 124, in 
> not_a_hack = CSGORadar()
> File "csgo_hack_pygame.py", line 30, in **init**
> if self.process.get_module_size("client_panorama.dll") != offsets["modules"]["client_panorama.dll"]["size"]:
> KeyError: 'modules'

how did you solve it?
